# Generated by Django 4.2.6 on 2024-02-24 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('quantity1', models.CharField(max_length=100)),
                ('quantity2', models.CharField(max_length=100)),
                ('quantity3', models.CharField(max_length=100)),
                ('keyfeatures4', models.CharField(max_length=100)),
                ('manufacture_details', models.CharField(max_length=100)),
                ('custemail', models.CharField(max_length=100)),
                ('custnumber', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='eshop/static/images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categories')),
            ],
        ),
    ]
